version: "2"
services:
  static:
    build:
      context: "client"
    ports:
      - "8000:80"
      - "4430:443"
    volumes:
      - ./client/static/build:/usr/share/nginx/html
    links:
      - game
    restart: always
  redis:
    build:
      context: "redis"
    restart: always
  game:
    image: "game-ringofworlds"
    links:
      - redis
    restart: always
