version: "2"
services:
  static:
    build:
      context: "client"
    ports:
      - "80:80"
      - "443:443"
    restart: always
  redis:
    build:
      context: "redis"
    restart: always
  game:
    image: "game-stormcards"
    ports:
      - "9160:9160"
    links:
      - redis
    restart: always
