version: "2"
services:
  static:
    build:
      context: "client"
    ports:
      - "80:80"
      - "443:443"
    links:
      - game
    restart: always
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "webapp"}]'
  game:
    build:
      context: "server"
    env_file: "prod.env"
    restart: always
    labels:
      com.datadoghq.ad.logs: '[{"source": "game", "service": "game"}]'
  datadog:
    image: "datadog/agent:latest"
    env_file: "prod.env"
    links:
      - game
      - static
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
