version: '2'
services:
  static:
    build:
      context: .
      dockerfile: Dockerfile-static
    ports:
      - "8000:80"
  game:
   build:
     context: .
     dockerfile: Dockerfile-game
   ports:
     - "9160:9160"
