version: "2"
services:
  static:
    build:
      context: "client"
    ports:
      - "80:80"
      - "443:443"
    links:
      - game
    restart: always
  game:
    image: "game-hubris"
    env_file: "redis/redis.prod.env"
    restart: always
