FROM arekczarnik/docker-circleci-haskell
MAINTAINER Rogan Murley <rogan@roganmurley.com>

RUN apt-get update
RUN apt-get install -y --no-install-recommends nodejs-legacy npm
RUN npm install -g gulp elm
