resolver: lts-7.0

packages:
- '.'

extra-deps:
  - guid-0.1.0
  - scotty-cookie-0.1.0.3

flags: {}

extra-package-dbs: []

docker:
  enable: true
  run-args: ["--net=bridge", "--publish=9161:9160"]

image:
  container:
    name: game
    base: fpco/haskell-scratch:integer-gmp
    entrypoints:
      - ringofworlds
