#!/bin/bash

pushd redis
openssl aes-256-cbc -d -in redis.prod.env.secret -out redis.prod.env -k $RINGOFWORLDS_SECRET_KEY
popd

pushd client/ssl
openssl aes-256-cbc -d -in www.ringofworlds.com.ca-bundle.secret -out www.ringofworlds.com.ca-bundle -k $RINGOFWORLDS_SECRET_KEY
openssl aes-256-cbc -d -in www.ringofworlds.com.key.secret -out www.ringofworlds.com.key -k $RINGOFWORLDS_SECRET_KEY
popd
