#!/bin/bash

openssl aes-256-cbc -d -in prod.env.secret -out prod.env -k $RINGOFWORLDS_SECRET_KEY

pushd client/ssl
openssl aes-256-cbc -d -in www.galgagame.com.ca-bundle.secret -out www.galgagame.com.ca-bundle -k $RINGOFWORLDS_SECRET_KEY
openssl aes-256-cbc -d -in www.galgagame.com.key.secret -out www.galgagame.com.key -k $RINGOFWORLDS_SECRET_KEY
openssl aes-256-cbc -d -in www.ringofworlds.com.ca-bundle.secret -out www.ringofworlds.com.ca-bundle -k $RINGOFWORLDS_SECRET_KEY
openssl aes-256-cbc -d -in www.ringofworlds.com.key.secret -out www.ringofworlds.com.key -k $RINGOFWORLDS_SECRET_KEY
popd
