#!/bin/bash

name=$1
set -e

if [ $# -eq 0 ]; then
    name=$(git rev-parse HEAD)
fi

echo "Building client code..."
pushd client
gulp build --production
popd

echo "Creating server image..."
pushd server
stack image container
popd
docker save -o .images/game-hubris game-hubris

echo "Provisioning server..."
docker-machine create --driver=digitalocean --digitalocean-access-token=$DIGITALOCEAN_ACCESS_TOKEN --digitalocean-region=lon1 --digitalocean-image=ubuntu-14-04-x64 $name
eval "$(docker-machine env $name)"

echo "Copying image to server..."
docker-machine scp .images/game-hubris $name:game-hubris
docker load -i .images/game-hubris

echo "Building compose..."
docker-compose -f docker-compose.prod.yml build

echo "Booting compose..."
docker-compose -f docker-compose.prod.yml up -d

echo "Flipping floating IP..."
./scripts/flip $name

echo "SUCCESS!"
