#!/bin/bash

pushd redis
openssl aes-256-cbc -e -in redis.prod.env -out redis.prod.env.secret -k $RINGOFWORLDS_SECRET_KEY
popd

pushd client/ssl
openssl aes-256-cbc -e -in www.ringofworlds.com.ca-bundle -out www.ringofworlds.com.ca-bundle.secret -k $RINGOFWORLDS_SECRET_KEY
openssl aes-256-cbc -e -in www.ringofworlds.com.key -out www.ringofworlds.com.key.secret -k $RINGOFWORLDS_SECRET_KEY
popd
