#!/bin/bash

openssl aes-256-cbc -e -in prod.env -out prod.env.secret -k $RINGOFWORLDS_SECRET_KEY

pushd client/ssl
openssl aes-256-cbc -e -in www.galgagame.com.ca-bundle -out www.galgagame.com.ca-bundle.secret -k $RINGOFWORLDS_SECRET_KEY
openssl aes-256-cbc -e -in www.galgagame.com.key -out www.galgagame.com.key.secret -k $RINGOFWORLDS_SECRET_KEY
popd
