#!/usr/local/bin/python3
import os
import sys

import requests


def get_droplets(token):
    req = requests.get(
        'https://api.digitalocean.com/v2/droplets?tag_name=ring-of-worlds',
        headers={'Authorization': 'Bearer {}'.format(token)},
    )
    return req.json()['droplets']


def delete_droplet(token, droplet):
    req = requests.delete(
        'https://api.digitalocean.com/v2/droplets/{}'.format(droplet['id']),
        headers={'Authorization': 'Bearer {}'.format(token)},
    )
    return req


def main():
    token = os.environ.get('DIGITALOCEAN_ACCESS_TOKEN')
    name = sys.argv[1]

    for droplet in get_droplets(token):
        if droplet['name'] != name:
            delete_droplet(token, droplet)


if __name__ == "__main__":
    main()
